project:
  type: website

website:
  title: "memex"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/OzwaldCavendish
      - icon: linkedin
        href: https://linkedin.com
format:
  html:
    theme: vapor
    css: styles.css



