project:
  type: website

website:
  title: "memex"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MartinChrisWood
      - icon: linkedin
        href: https://www.linkedin.com/in/martin-wood-822655288/
format:
  html:
    theme: vapor
    css: styles.css



