---
title: "Snap shot"
author: "Ozzy Cavendish"
date: "2023-08-06"
categories: [science-fiction]
draft: true
---

# Snap shot

## Hunt

My main drive burned furiously at an angle to the star at the center of the system as I decelerated into a scouting trajectory.  The white dwarf’s stark glow looked to my electronic senses sullen and dull, next to the torch of my fusion engine. The star burned with fusion too, but dimmed by layers of gasses and haloed ephemeral gaseous tendrils, while my drive’s flame cut clean into space.  A quick virtual “snap” and the image dumped to the collection in my external memory.  I screamed across the orbital path on a rocky inner planet, a part of my enhanced mind considering what the sight from the surface must be, a new pinpoint comet briefly outshining the sun before whipping past on to a close inner circuit of the star system.

Quick diagnostics over myself confirmed I was holding up under the 100 G burn.  Integrity sensors showed green right across my spherical 50 meter hull, and out across the two manoeuvring booms that jutted from my flanks.  The rotation thrusters at their ends, able to spin me on to a new trajectory within milliseconds, reported green also.  The fibre-optic nerve layers themselves reported ready, echoed by enthusiastic confirmations from myriad individual smart weapons in their bays. The information poured into my now-silicon mind along circuitry that had, long ago, carried organic signals from a flesh body.  I had long since decided I loved the clarify of my new hardware.

I returned my attention to the hostiles ahead.  I had only detected them while poking through this system’s Oort cloud thanks to a chance blemish on one of their hulls.  Some back-of-the-envelope maths performed in the interminable parts of the chase suggested less than 1cm of the camo-coating on one hostile had been scratched off.  The damaged side remained visible as I passively circled through the Oort debris.  Three torches lit up when they finally detected me incoming.

Now finally after chasing the trio down towards the star they had turned to fight.  If they had split they could have guaranteed two would escape, but they were supposed to be fighting us eventually somewhere.  They had three-to-one odds, and perhaps even a little camaraderie featured in their decision trees.

The hostiles spread out a little and let me draw closer.  Who chases who doesn’t really matter in a space battle, only relative velocity – their move was exactly equivalent to accelerating towards me themselves. In a contest like this, with everyone’s velocities at stellar speeds, a battle was more of a joust.  One pass, and whoever had deployed their ballistics and munitions most effectively would speed out the other side intact.

I pinged my chosen munitions one last time, the weapons excitedly screaming back that they were armed.  Shaped mini nukes with simulated intelligences operating on purely fibre-optic processors.  Relatively immune to electromagnetic interference and smart enough to dance through a metal swarm.  I carefully did not ping my Wingman, flying in somewhere behind me on some very basic instructions.  He’d have to stay dark.

Our closing velocity still measured in the tens of kilometers a second – slightly fast even for my speed-intelligence, a little slow for their speedier Simulated Intelligences.  This compromise had been achieved through our jostling to set the intercept as I plunged in-system towards them.  We would be able to engage for all of ten seconds but at our processing speeds that would subjectively stretch.  I was already jacked to a framerate orders above normal human experience - I couldn’t multitask like an SI but speed me up enough and I could get a lot done in serial.  Plus, we human minds have that creative edge still.

## Fight

I careened towards a glowing red plane in my navigational mind’s eye that marked the edge of the expected engagement zone, and enjoyed the feeling of a mental shit eating grin.  At intersection I threw open weapons bays and my point nukes spewed out en-masse, spiralling manically on mini fusion torches at speeds that made me look like a lumbering planetesimal.  They spread themselves randomly through the void ahead and joyfully picked targets to dive on. My forward cameras operated on spectra far beyond that a biological eye could perceive.  They picked out the incandescent high-frequency fireflies of the enemy’s deployed nukes, twinkling as they gamely stuttered their drives to confuse tracking.  Panning down to infrared let me follow the multitude.  A moment later hot shrapnel spewed from the three targets, to confuse the view.  This was followed by a swiftly spreading shield of fine inert metal debris, barely more than silt on the wind but with mass enough to rip a hole through a nuke or some of my hull at these speeds. The particles were almost undetectable, radiating at the ambient temperature of their former host ships.  

My spin thrusters jimmied me towards a thinner looking path as my missiles went frantic in search of holes. By now the three must be wondering why I hadn’t deployed a swarm shield of my own, they might well suspect I’d gone all in on missiles, expecting to ambush enemies by stealth on my hunt through the Oort.

Nuclear explosions bloomed in staccato as our munitions finally met.  Not one of the mini nukes got within five kilometers of an enemy ship, but over two thirds detonated.  A fraction had found a line that would at least let them burn through enemy nukes or poke holes in the shrapnel screen while pouring radiation onto the hulls of the enemy ships from afar.  A wall of nuclear flame erupted between us and swamped even our machine eyes.  Another virtual “snap” as the tremendous sight was stored.

Wingman finally swept through the fight.  A vessel like my own, but piloted by a subservient AI, instructed to fly in directly behind me with its presence masked by my fusion torch.  While I decelerated the entire way, Wingman had retained a far greater relative velocity and had just now caught up.  It didn’t bother with mini-nukes and simply sprayed a metal swarm ahead of its hull.  As the Wingman plunged in dark and cold behind the radioactive mist, my eyes noted a desperate last full burn from each hostile’s evasion attempt. Two enemy units were instantaneously shredded as Wingman ripped past, red-yellow glowing streamers of molten metals tearing away from them as half their mass was gouged off.  I dived though a sparse hole in the enemy metal swarm, a requisitioned chain of smart nukes exploding ahead of me to burn a cleaner path.  A few gouges and one submunition hatch damaged but I was through through, flashing past my final opponent.  

I spun one-eighty and burned up towards the enemy, grim determination to finish this now colouring my mind.  The final battle with them would be slower.  If they ran, they must know they’d eventually be cut off by me and my wingman working in concert.  Their best of their admittedly terrible options was to face off against me as soon as possible in the hopes I’d at least taken some damage in the last fight.  After that, with just one enemy they could jig out of the system or have better odds in a face-off if they were feeling belligerent.  But we both now had to undo our relative velocities over a short distance, and that’d make for a long time within engagement range and a drawn-out battle.  In those situations the ultimate arbiter was logistics, who had the most munitions to burn against those of the other?  I’d already deployed enough nukes for three.

## Trap

As I burned for my enemy, and Wingman began to swing back outwards towards our orbit, my “weirdness” detector tripped.  This algorithm was a personal innovation.  A non-standard product of being surprised a few too many times by new and unanticipated tricks by our long-time opponents.  It was a fairly simple neural net, not even quite SI level, that would predict an enemy’s actions and movements for a given situation.  It didn’t necessarily understand everything but I had an alert set for if the enemy deviated significantly from its simple expectations.  That’s enough to know that there’s a factor at play that’s not in the model, and if I don’t know what that extra factor is then someone’s playing games.

In this case the model was objecting to the enemy’s total velocity.  It should be lower, it insisted.  It’s diving around to be sure, to prevent my firing a missile straight up its otherwise predictable rear, but it’s suddenly doing that less, giving it a higher total velocity in return for risking a shot up the backside.  I jacked my framerate to think even faster.  The processing speed was now unsustainable and error boxes cropped up in my perception as the predicted temperature of my artificial brain zoomed into realms uncomfortable for silicon. Further errors complained of the disjoint between my speed and that of the ship systems I commanded, but I only needed to buy myself some seconds to ponder and I’d learned how crucial it could be to ponder quickly.  It was jigging too little.  That meant we’d meet later, if I didn’t get a missile to it.  Which meant it wanted to meet later and thought that’d be advantageous.  It’d make no difference to our relative intercept, so what was the advantage?  It wanted me in a specific place at a specific time.  I thought of my own trick with Wingman and immediately spun myself ninety and burned at evasion speeds.  

My sensors picked up tens of blips travelling at truly ludicrous speeds for in-system traffic, whipping outwards from the star and upwards from below the plane we occupied.  They flew past just like wingman, and I caught just a single blurred hint of the infrared mist of the accompanying metal swarm.  Ominously those blips seemed to be significantly larger than myself or my prey, a new class of opponent.  But how were they here?  I plotted vectors as my machine-mind’s eye zoomed out.  

Highly elliptical orbits.  These things had been put in place beforehand, swinging into and out of the system, building up tremendous, almost interstellar velocities as they plunged in freefall towards the white dwarf before whipping round the far side and cruising out again.  Based on the ease with which I’d been lured into the path of a cluster, I made some quick calculations.  Tens of thousands of these, dispersed through the system.  The defence machines no doubt make some tiny adjustments at perihelion on the far side from their target and suddenly there’s a weapons platform headed for your throat at speeds that challenge even a machine brain’s reaction time.  All while largely inert and therefore almost invisible until it’s on top of you.

This was a new kind of defence, and incidentally an ideal way to trap troublesome scouts.  Just rub off a bit of camo-coating and lure them down to where the defences are spun up to combat velocities. Only I’d been a little quicker than they thought, and I’d had Wingman as my own trump card.

## Escape

My priorities had changed in a flash of high velocity terror, and now I angled myself up out of the system back towards interstellar space.  My drive on full burn, my erstwhile prey was disappearing behind me before it realised I was scrambling for the stars.  My overall trajectory was simple – up and out, leaving my enemies as small a window to counter me as possible.   Wasn’t sure of my odds, with heavy ships slingshotting around their star they could probably fling out a few on pursuit.  I began to sense the ignition of fusion torches across the sky behind me as signals went out between ships, the light of their reactions then making their way to my detectors.  Five different lights.  They could use the residual velocity of their orbits past the star to catch up to me, but they were ultimately larger, their mass leaving them only the one chance to close before I escaped.  I could manoeuvrer on tangential axes faster, but they could predict and had five combatants with which to cage me.  I put the odds at  alarmingly less than even, given they could also carpet my trajectory with smart-missiles.  

As I slowed my processing speed, cooling my circuits in preparation for further combat, I tight-beamed a long message ahead of me into interstellar space.  The odd scattered photon would let my enemies know I was sending information but they had no idea what, or to who.  The pulsed light pumped a backup of my own mind across interstellar distances, but not before a situation report and recordings of everything I’d encountered in this star system.  Sandwiched between my report and my mind went my new photos.  Images of the streaks of fusion torches chasing past the Oort objects.  Directed radiation blasts blooming across the space between fusion warships.  Impressionistic prints of elliptical orbits bearing down on my own darting trajectory.

As I accelerated upwards, preoccupied with my own escape, the message flew ahead of me.  Subjective months later the message finally struck the sensors of my home battle carrier.  The huge and ancient warship was already racing towards the hostile star and pouring on more speed in a lightyears-long pounce.  As the data came in, the governing minds plotted a blistering course across the orbital plane of our prey.  Prediction engines calculated probable orbits of the defensive weapons I’d observed, and duly arranged the scattering of the ships’ onboard munitions.  It carried more fighters like me, but they wouldn’t be deployed until after the initial strike, accelerating furiously simply to return to whatever remained of the enemies the carrier would dive past.  Smart munitions were primed to scatter at near light speed.  They would partake in an instantaneous assault on every predicted enemy position at once.  A run up between the stars ensured my comrades would be coming upon them fast enough to preclude any possible evasion.