---
title: "Pretender at the Walls"
author: "Ozzy Cavendish"
date: "2023-08-06"
categories: [science-fiction]
draft: true
---

# The Pretender at the Walls

A tale of blasphemous pragmatism.

## What does it do
General Merrick's wizened gaze took in the impressively tall and unforgiving city walls before him.  Dark, precisely cut stone presented a blank-faced, looming barrier that upon arrival weeks ago had immediately scuppered the marching army’s half formed plans for scaling their heights.  Rumours of the imposing defence had not, as had been assumed, been greatly exaggerated.  From the old general’s vantage on a rise to the West, the walls curved smoothly back and away to the North and South to eventually circle round and entirely encapsulate the regional capital of Newtown. Naturally for a place with such a name the city had been inhabited for nearly a millennia, though these latest defences were just three hundred years old. Atop the walls armed men paced between the wall top embrasures, sweating heavily under leather jerkins as they tried to look vigilant and focused in the melting summer heat.  Two weeks of scorching sun was taking its toll on their will, some slumped at their posts, no one corrected them.  Their eyes were still drawn frequently to the army now encamped in plain sight of them, a threat that Merrick had not yet found a way to realise for them with those damned walls in the way.  Sweaty hands griped heavy spears, dogsbodies sidled between them to check on the bundles of arrows and other supplies stored neatly beneath the merlons. As on previous wall-staring sessions, Merrick noted their oddly miss-matched equipment.  A militia composed of whatever guards and men were to hand, the bandoliers were the only uniform they had. 

Merrick frowned. Aged creases across his forehead and around his eyes deepened. 
“Yeah, still not happening” he muttered.  His gaze flicked to the white-robed man beside him, his mood becoming thoughtful.  His sun-browned countenance shifted from its default perpetual disapproving frown to a more set, interrogative frown that his companion recognised, with sinking heart, as that preceding many painful discussions. The Priest Andrew, Prophet and Embodiment of the Will of the Light, mentally braced himself and then sallied to give Merrick his best flat stare. 

“What this time?” he demanded; better to go in first. “What is it now?!”.  Two weeks of overheated inaction had taken its toll on his mood, too.

Merrick nodded slowly, ordering his own thoughts as his sharp gaze marked the developing lethargy in the sun-baked city militia in their red bandoliers atop the walls. Those dark stones. He bet they were baking hot by this point, wouldn’t even cool fully at night. 
“You say we need the temple in this city.” 

“Yes. Vital. Heart and soul of the nation.” Andrew drew breath, mentally selecting a few inspiring stories of the relics hosted within the temple, the better to bolster Merrick's zeal in the attack that, as Andrew had pointed out previously several times, Merrick had not yet carried out.

“What does it do?”

“... sorry?” the priest's lungs gently deflated through the word, having anticipated needing more air than that.

“What, precisely, does it do?” enunciated the general's clipped, gravelly voice. “I have been staring at this nigh-on-impregnable city for two weeks now while we ‘gather forces’ and the scouts map the walls. Depressingly circular and continuous by the way, no weaknesses or damaged points or even conveniently rusted gratings. The thing I notice, see, is that the place doesn't do anything. It's a trading town sure, but the people here don't grow crops. There's a river, kind of, but it doesn't lead anywhere important. No major military presence, just a militia mostly of tradesmen's guards. No critical infrastructure, that's all handled from the country's capital South of here. So, what does this temple contribute exactly? Do we need one?”

Andrew's jaw swung gently as his mind tried to work its way around these brutally pragmatic observations. His levered his jaw back in to place as he rallied pertinent facts; “There are relics in there! Ancient symbols of our faith, focuses for the prayers and dreams of millions!”

“Any of them magic? Something that explodes?” Merrick asked hopefully.  He’d heard of powerful ancient relics, power hopefully meant “can remove a wall”.  Andrew had not been forthcoming on the matter.

“No.” replied Andrew, exasperated,  “the Ancient Vestments of the Light and the Crown of Light are objects of reverence, not... ballistics? Why on earth would a church have exploding relics?”

“Does it contain more holy weaponry perhaps?” continued the general, “We could use more magic swords!  Just the one magic sword that can cut literally anything has been a help but in an army of tens of thousands there's only so much it can do for logistics.”

“No...logistics?” Andrew echoed, failing to connect the Sword of Light, Holy Relic of the Kingdom of Light that he had personally handed to the general (finally) with the noisy and smelly frenzy of activity that was a military camp in action. His jaw hovered, ready to clench in anger or fall agape as the situation demanded.  Merrick had an appreciation for how much work Andrew’s jaw did in their conversations.

“It cuts anything!  But it takes time for the divisions to trim down arrowheads and blades, even with it set up in that workbench the artisans clapped around it. Lets the engineers use it to cut the fiddly bits of siege weaponry too.”

“... the sword is clamped in a work bench.” The priest's jaw decided to go with clenching shut, his face was turning red anyway so go with the mood.  “So what’s that on your hip?” he demanded, tensely.

“Replica the lads knocked up.  Best not let too many people know the real value of that thing.  This one here isn’t magic, won’t cut someone right in half like the real one, but generally you just need to poke a hole in a bloke to kill’em – cutting someone in half just creates a mess, ruins your footing.

“Now if we had a few more magic swords, we might even look at letting the sappers have one to play with” Merrick conjectured with sudden enthusiasm,  “they say it could help with the enemy walls. Lots of mud to dig through first, cutting sword's no good for that, but stone’s the tough part obviously.”

“That sword is a unique and powerful relic!” Andrew responded, aghast.

“Only the one then? Damn. We'll use it while it lasts.” Merrick said.

“It is an indestructible embodiment of the Will of Light!”

“Might last a good while then.”

The general turned from the walls finally, looking past the red-faced priest and his well clenched jaw to their own army camp. The force he'd gathered, some ten thousand soldiers and fifteen thousand people in total (army camps just bloat like that), had spread itself firmly but orderly across the low rise facing the city. Higher valleys and green hills were at their backs, and to their front before the forbidding walls splayed a wide, open plain described by his tacticians as “an ideal killing field for them, don't go over there”. Priest Andrew had thought it a nice clear space in which to mount their glorious charge and take the city.

The general had not bothered to inquire what the priest thought horses would do against stone walls. In fairness his limited cavalry tended to assess situations in the same manner. They seemed more focused on the process of charging while Merrick had gotten old by first thinking about how charges might end. His rise to his current rank had been slowed by rivals deriding him for asking awkward questions like “would we win?”. His rise had also been almost inevitable, with those rivals suffering a steady attrition over the years that left posts free for a man willing to take a little less glory and build a little more pension. He was not an incompetent leader – rather the opposite – but he did not fool himself into believing his careful and logical manner were a desired characteristic in his nation's rather aristocratic military. Old families ruled, and they had a surplus of sons and a need for stories to go with their embellished portraits.
Merrick reached down and idly fished a dark grey stone from the ground. It looked to be of a kind with the blocks comprising the city walls he faced. Yep, too hot to palm after a day in the sun. He fidgeted it from fingertip to fingertip, thinking.

A figure trudged up from the camp to their watch. Dangling tools clattered as the man stomped mechanically up to them, identifying the man as the chief engineer even before the signature broad blonde moustache was in view. “You asked to see me sir?” the engineer grumbled. It wasn't personal, he just grumbled regardless.  He'd grumbled through his own wedding vows.  A natural grumble of a man.

“Yup. You've been hard at work on siege equipment, ladders and the like?”

“You know I have sir.” He said, tersely.

“Very good. New plan. Break them down for transport. Have a few of your lads grab a barrel of tar and any odd bits of wood and meet me by those rocks over behind the camp...”

## The nice thing about big tall walls
Corporal Hendy found himself reflecting hard upon his choice of soldiering as a career as he clung to an improvised handhold, two thirds of the way up the enemy's defensive walls, in near complete darkness. While his right hand clutched at the chunk of wood now affixed to the hot stone with tar, his left carefully unhooked another goo-backed piece from the hoop at his belt and pushed it in to place above his head. The heat still radiating off the sun-baked wall was just enough to render the tar malleable.  The tacky goop worked its way into the grain of the rock slab and fixed in place. A tug confirmed it had bonded and Hendy hauled himself up to the next haphazard hold to repeat the process. The nice thing about big tall walls, he thought, hard for guards to see down over the top even if there was any light to see with, and that wasn’t the case on this particular cloudy night.  The faintest pearlescent lightening marked the hidden moon above, and all below was in darkness.

He remembered, as his aching arm forced another block into place overhead, the day that his own ragtag unit had been approached by Merrick and his growing force.  He and his had been squatting on the mountainside they’d been forced to call “home” since the last discharge.  Small outfits like his were fairly common; they’d scraped a living in the forces of whichever petty lord around the highlands had suddenly found issue with their neighbour.  Small time engagements, lots of guarding with a new colour of bandolier on, occasional terror as a lord got a bit keen and ordered an actual charge; he’d grown quite skilled at yelling fiercely while taking slightly shorter strides than a lord’s own men.

“Time to find yourselves a future!” Merrick had said. His sharp eyes didn’t blink as they locked with his prospective recruits. The general stood smartly, a slight stoop in his old back serving to enhance his uncanny resemblance to a bird of prey fixed upon something small and furry.   The mob had looked on very politely, keen awareness of the thousands of troops standing just behind the old man inspired a certain sober attentiveness.
“Clearly your own plans aren’t working out.” Merrick had continued.  Hendy had suppressed a snort.  This was true.  The last lord had kicked them out in a patch of land between two well-armed fiefdoms after a minor pay dispute.  They were all decidedly on the hungry side.  A white-robed yet haggard priest with an oddly over-muscled jaw had looked on doubtfully at the scruffy figures, taking in the sight of even skinnier pigeons on sticks over small fires.
“Try my plan.  It involves marching and actual fighting,”  Merrick had said, eyeing their meagre gear, “but I do not waste my men”.  Hendy had grimaced at that, he had made a living by being designated arrow fodder and then carefully placing himself just a little further to the left.
“And,” Merrick had added, with a decidedly predatory grin, “I have never, ever been accused of being a noble.”

Pulling himself from the memory, a good hour's struggling up the fortifications found the Corporal sealing the last hold in place just below the wall top embrasures.  He held still a moment as muttering guards ambled past. He controlled his breathing as best he could, tensing.  His arms trembled alarmingly as they passed on, remaining unaware, and he finally began the descent. It had been painful, exacting and exhausting work and he fought to convince his skinned hands to grip and his arms to hold, as he lowered himself steadily. Hendy barely made it down, dropping the last two metres to the grass with a belatedly stifled groan.
The rest of the small squad pulled him up, patted him roughly on the back, propped him against the hot wall and moved with urgency to scurry up his handholds. The rapidly formed group had already coined themselves the Sneaky Bastards, after the general had demanded of their commanding officers that they find “the smallest, lightest, sneakiest bastards you have, good with a knife ideally, and not too bothered about heights.” Hendy himself was slim and short at a little over five foot, stayed quiet and treaded lightly. He had already found himself singled out and put to use scouting around the marching column.  He’d mentally cussed through the entire briefing on the mission for which he’d been told be was now a “volunteer”.

As Hendy recovered, the others filed past him and upwards at a rapid clip. They fussed their shiny new red bandoliers out of the way of their arms as they hauled themselves aloft.  The bandoliers were likely only approximately right, the best the army could knock up with only a distant look at their enemy’s colours on the walls.  The last man up the wall carried a bulky backpack, his narrow face pinched in concentration as his wiry arms reached for the lowest holds. Hendy reached out and shoved a corner of white cloth back under the pack’s leather cover. Minutes later, the new force’s safe arrival at the top was confirmed to him by the quiet squelching crack of a dead guard splatting to the ground some metres away.  No cry, Hendy thought approvingly, the now flattened guard's throat presumably had been slit.

Hendy idled, in the painfully tense way of a soldier forced to wait in an incredibly dangerous position. If anything went wrong the walls would immediately be swarming, with torches cast down and keen eyes looking for any sign of attackers. An hour crawled by, stretching interminably in Hendy's mind as he continued to hear in every rustle and whisper his own imminent discovery and death. At long last a crack and hastily stifled cussing sounded above his head and a tar-covered corner of wood pinged off his helmet. A bundled white roll of fabric thumped gently into the grass next to him, followed momentarily by a crown.

“We done here?” Hendy hissed up into the dark.  He gathered the cloth bundle and prepared to move fast, wrapping the crown.

“Feck yes, we left three corpses and couldn’t do more than drag them into an alley, so look sharp!” a hoarse whisper floated back in response, followed by boots hitting the ground. “Turns out, those bandoliers have fancy frilly bits. Only took one guy to spot us passing a torch.” the man spat out, angry and not a little frantic around the eyes.  Scuffling above signalled the rest of the squad escaping down the wall.  A bell started clanging somewhere and the last few men chose to drop dangerously several meters to the ground taking a rough fall rather than risking delay.  Hendy stifled his own cursing and hauled the last men to their feet before frantically shoving them towards the tree line.

Barely thirty seconds later as more bells took up the alarm, torches began to flare along the battlements.  They shone out over an empty field, the infiltrators having already legged it across the plains and lost themselves in the darkness.

## Very good sir

Andrew woke to a different clanging from within their own camp. Clattering and clanging, far too early in the morning. He wondered blearily what was going on, his sleep-gummed eyes registered a soldier in his tent, steadily packing his travel desk and various accoutrements.
“You - wh-what?” Andrew attempted, a fair attempt at a sentence just two seconds into wakefulness.

“Very good sir” said the soldier, taking pity on him and inferring the sense of the question as being ‘What the hell is going on soldier?!’. “We're moving out in twenty minutes sir, leaving a few scouts to watch the city and marching onwards to the coastal city. Should be a sight to see sir!  Called Newport. Been there thousands of years.  Big place.”

Wakefulness crashed down upon Andrew like cold water to the face.  Unpleasant, in other words. He said no more as he grabbed frantically for clothing and hurried off to find Merrick.
He discovered him promptly, stood on a crate surveying the camp as it disassembled itself.  The manoeuvre was one the soldiers were well versed in, and was being executed with only minor hiccups that nevertheless drew Merrick’s immediate ire.  “Get those bleeding carts on the move, you've jammed up the fecking thoroughfare!” Merrick hollered. In fairness he didn't generally drive his men through sheer volume, but in the clamour of a mobilising army, hollering was a necessity.

“Merrick!” Andrew hollered frantically, his worried bellow outcompeting the shouts of the squad hauling ineffectually at a stuck cart.

“Ah, you're up!” Merrick shouted, turning a little but keeping the beleagured squad firmly in sight. “I sent men to pack your kit, I know you fuss about the gold bits and pieces in your priest box, can't be having delays today! Too long here already!” Merrick hollered back.

“Priest box? Wait, the communion set? Never mind!  Why are we going!? The temple is right over there!” Andrew waved wildly in the direction of the city walls that he could see were still standing. “The temple must be claimed!”  This last wail was lost in a scream of “Heave!” from the team at the stuck cart.

“Well, we got the loot out! I mean, the relics, whatever, they're in a crate somewhere in this rabble.” Merrick hollered contentedly, gesturing dismissively to the carts.  These now inched forward as the front of the line got underway. “With that we're done! On to a city with actual strategic value, a port right at the straight into the Evanescent Sea.”

“You - wh-what?” Andrew hollered in confusion. The back of his mind registered how useful that phrase was today.

“The relics! You said the temple's value was some relics right? Some kind of dress and a crown. Sent in infiltrators over the wall, brought 'em out. Temple sorted. Much more efficient than a battle. Onwards!” Merrick hollered enthusiastically, over the tramping army. “Newport’s really just merchant guards, with no possible military reinforcements.” he raised a middle finger to the walls they’d been staring at for weeks. “Enough men to make the city impossible to take, but not enough to march out and trouble our rear. We'll keep an eye out but move right on past!” Merrick stepped gingerly from the crate and moved off to holler the camp kitchens apart.
Andrew stared after him as his brain spun these developments into order. No battle, no temple. No grand altar displaying the relics and by their possesion granting them divine right to rule. Just the robe and the crown, in a box, as they marched to war. For some filthy port at the connection between the two major seas? ...ah.

A little hunting through the column and he found the chest with the “loot”. It was guarded by a seedy, decidedly surly looking squad of cut-throats who acted all the more aggreived after going from a risky infiltration mission straight on to a forced march with no sleep.
After explaining that he was in fact the army's high priest, and that these items were decidedly his responsibility, an alarmingly varied collection of knives were removed from his neck and returned to their sheaths and he was reluctantly allowed near. He found the robe and crown to be mercifully intact after their adventure the previous night and Andrew’s heart finally stopped trying to choke him and settled back down into its proper place. The robe glimmered just a bit too brightly where sunlight struck, a clue to its supernatural nature. The crowns glow at least could be passed off as unusually shiny gold? Andrew sighed. He supposed he'd have to tell Merrick what the items could do now. He doubted they'd see much fighting though, the only use the last High Priest had found for them was checking what weather was coming for the abbey.  He silently berated himself for the disrespectful thought and moved after the forming column.

## What the items could do now

Andrew sat on a rocky outcrop, tiredly eyeing the ongoing siege across the bay.  He yawned widely, working the tension from his jaw.  His legs were a mass of pain after the march from Newtown, but at least he wasn’t expected to go from that straight to fighting for the port, like their soldiers. They had seemed to manage, by this point the battle was decided and their army roamed the outer city freely. The port had too few defenders to start with and this weakness had been compounded by old, crumbling walls with an abundance of rusty grates and obvious weak points for Merrick to be clever about. An expanding population and lack of governance had holed the fortifications like cheese, years of short-term concerns and multiplying homes seeing the defences treated as free building supplies. Smoke columns rising from the cove behind the buildings told the fate of the few ships that had tried to sit out the siege in the harbour.

On the march across to the coast, Andrew had explained what little the relics could do.  Merrick had pinned him with those hawkish eyes fou an uncomfortably long moment.  Then he had started cackling gleefully, before seizing the items and their storage chest from him, moving it to the centre of the camp and tripling the guard on the artefacts. He had been chuckling evilly the entire time, dragging officers into his wake ready to carry his orders. His first use of the items had revealed unto him Great Truths, specifically the poor defences and small numbers of his target, and the existence of columns of enemy reinforcements marching in along the coast from the East. Barely half an hour later four large squads of rangy, dangerous looking men – of which Merrick seemed to have an overabundance – had picked black powder charges and departed double-time to intercept the marching columns. 
Evidently their guerilla strikes along the enemies marching lines had sufficiently delayed the approaching army. Merrick’s forces would be in to the port and reinforcing it days before the marching troops arrived and they would find themselves outmanoeuvred and without shelter or the fort's provisions.

Now as his men breeched the inner walls the craggy general stood and watched from afar, crown askew on his head and robe tied crudely like a belt around his waist (he'd refused to wear a “dress”). A faint grin hung on his weathered features as his eyes flickered, the regalia's power letting his mind's eye roam freely across the battle. Runners came and went in a steady stream as he muttered instructions to be passed to his squads, his perfect information translated to military action on the ground. One of the runners dashed up with his Sword of Light, now thoroughly dusted with iron and rust shavings.

“Sir, sappers send their thanks, made short work of the gratings and gate hinges! They just cut a hole right through the base of the keep–”

“I know, soldier. Crown! Be off with you.”  Merrick said.

“Sir!” the runner ran, abashed.

“Command!” Merrick said, “We're moving into the city!” He set off at a brisk pace towards the port’s landward gates. Soldiers scrambled around him to gather the maps and records that littered the command point tables even as guards scurried to place themselves around the marching general.

Andrew groaned gently as he levered himself to his aching feet and trudged after the migrating command centre. When he'd been charged with finding the Bearer of the Sword he'd been told he'd find the one who would “unite the lands”. He'd assumed this would involve collecting the regalia, a coronation, visits from the lands various self-declared lords to swear fealty and a long life of preaching from the Temple of Light most days. Saturdays would be reserved for gentle walks and some fine wines. This had proved painfully naive.  On his travels no less than seven of those lords had tried to capture and waylay him, while explaining (sometimes from the backs of pursuing horses) precisely which body parts he would loose if they were not in fact found to be the fabled Bearer. Years later, news that the sword had actually been found had triggered the prompt defensive coalescence of two new world powers out of the lords that littered the land. Both powers declared their pre-emptive rejection of “the Pretender” before the an actual Bearer had even been identified. 

By the time Andrew did find him, the man was fifty. The gnarled mercenary leader had expressed zero interest in ruling, and only decided to take on the task when it became apparent to him and his advisers that there was no scenario in which the lords would leave him to live out his retirement now they knew his identity. He'd sent men to call up some of his old army friends, almost casually assumed control of the nearest castle – killing the associated lord without seeming to notice – and then had the word “Pretender” embroidered on some of the nicer banners.  Merrick smirked indecently every time he passed them in the halls.  From there, he moved to seize every fort his advisers had deemed essential to securing the valleys Andrew had found him in. Only with the farmland safe and able to fuel his forces indefinitely did Merrick finally take the sword in hand.

Now, as Andrew watched the man advance on the conquered port city a year later, he began to feel he understood what his long search had been for. Had he found the bearer aged twenty or thirty, he supposed, those lords would have smiled and bowed, and then poisoned, stabbed or otherwise removed both Merrick and Andrew within hours. But Merrick was at the end of his career and the peak of his command, surrounded by loyal, well-armed and equally cynical men. He had been hardened and sharpened and trained in every aspect of large scale combat by the wars that the rumours of the sword had started. He possessed the decades of practical experience in warfare needed to unite a land that was never going to simply bow to the will of its own God.
Andrew sped to a jog, chasing after the General once again.